name: dupesweep
description: A personal Android app to find and review duplicate photos on your device.
publish_to: 'none'

version: 1.4.7+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.0
  photo_manager: ^3.12.0
  permission_handler: ^13.0.1
  image: ^4.0.0
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
